name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
filter-by-commitish: true
#header: |
#[![DOI](https://zenodo.org/badge/309495236.svg)](https://zenodo.org/badge/latestdoi/309495236)

template: |
  ## Changes

  $CHANGES
categories:
  - title: '🚀 Features'
    labels:
      - 'breaking'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'test'
  - title: '📝 Documentation'
    labels:
      - 'documentation'

exclude-labels:
  - skip_changelog

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  # major:
  #   labels:
  #     - 'breaking'
  minor:
    labels:
      - 'breaking'
      - 'enhancement'
  patch:
    labels:
      - 'maintenance'
      - 'bug'
      - 'test'
      - 'documentation'
  default: patch
