"""
This type stub file was generated by pyright.
"""

from pvandyken.deprecated.deprecated import (
    DeprecatedWarning,
    UnsupportedWarning,
    deprecated,
    fail_if_not_removed,
    set_config,
)

__all__ = [
    "DeprecatedWarning",
    "UnsupportedWarning",
    "deprecated",
    "fail_if_not_removed",
    "set_config",
]
