bids_dir: 'data'


pybids_inputs:
  bold:
    filters:
      suffix: 'bold'
      extension: '.nii.gz'
      datatype: 'func'
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run

analysis_levels:
 - participant

targets_by_analysis_level:
  participant:
    - ''  # if '', then the first rule is run

parse_args:
  --fwhm:
    help: >
      Set the full-width-half-maximum values that should be used for smoothing.
    type: int
    nargs: +
    default:
      - 5
      - 10
      - 15
      - 20
