import snakebids
from snakebids import bids

configfile: 'config.yml'

config.update(
    snakebids.generate_inputs(
        bids_dir=config['bids_dir'],
        pybids_inputs=config['pybids_inputs'],
    )
)

import pprint
pprint.pp(config)

rule all:
    input:
        expand(bids(root='results',
                fwhm='{fwhm}',
                suffix='bold.nii.gz',
                **config['wildcards']['bold']),
                    fwhm=config['fwhm'],
                    **config['lists']['bold'])


def calc_sigma_from_fwhm(wildcards):
    return f'{float(wildcards.fwhm)/2.355:0.2f}'


rule smooth:
    input:
        config['path']['bold']
    params:
        sigma = calc_sigma_from_fwhm
    output:
        bids(root='results',
                fwhm='{fwhm}',
                suffix='bold.nii.gz',
                **config['wildcards']['bold'])
    shell:
        'fslmaths {input} -s {params.sigma} {output}'
