rule smooth:
    input:
        'data/sub-{subject}/func/sub-{subject}_task-{task}_run-{run}_bold.nii.gz'
    params:
        sigma = '2.12'
    output:
        'results/sub-{subject}/func/sub-{subject}_task-{task}_run-{run}_fwhm-5mm_bold.nii.gz'
    shell:
        'fslmaths {input} -s {params.sigma} {output}'
